name: Deploy Prod

on:
  release:
    types: [ published ]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setting Local Properties
        run: |
          touch ./local.properties
          echo "${{ secrets.LOCAL_PROPERTIES }}" > ./local.properties

      - name: Setting Google Services Json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle
          versionName: ${{ github.event.release.tag_name }}

      - name: Gradle Build
        run: ./gradlew clean bundleRelease

      - name: Upload apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: FOne
          file: app/build/outputs/bundle/release/app-release.aab